### ISSUE TITLE
アルバイトへの明細発行

### ISSUE THREAD

**Issue by ytogo** [fjordllc/fjordllc#20]
以前データ入力をお願いした4名に対する話。

町田さんによる源泉徴収はしてないが、明細的なものが必要なんじゃないかという意見。（あとで問題にならないかどうか）

北島先生に応相談。

**Comment by komagata** [comment]
@ytogo 北島先生が毎月やってくれることになりました。

**Comment by komagata** [comment]
間違ってCloseしたのでReopen。

**Comment by komagata** [comment]
@ytogo これってどういう状態でしたっけ？

**Comment by ytogo** [comment]
昨日、ご相談した通りに必要になったら（東郷以外の方）北島先生にお伝えして、発行してもらうということでよろしいでしょうか。よろしくお願いいたします。
