### ISSUE TITLE
boughtitに1件投稿する

### ISSUE THREAD

**Issue by komagata** [fjordllc/fjordllc#22]
その後、良かった点と改善点（こうした方がいいんじゃないか）を下記に書いていただけるとありがたいです。

**Comment by ytogo** [comment]
良かった点は...
 
改善点（こうした方がいいんじゃないか）は...
商品登録を間違えてしまい、削除できなかったのでダブって作成してしましました。申し訳ないです。
気のせいかもしれないのですが、トップページの商品画像が若干縦に伸びているいるように見えます。

**Comment by komagata** [comment]
ありがとうございます。
