### ISSUE TITLE
過去の書類の整理

### ISSUE THREAD

**Issue by komagata** [fjordllc/fjordllc#24]
- [x] 7年以上前のものを捨てる。
- [ ] 分類する
  - 年度毎
  - 領収書（駒形、町田、フィヨルドに分ける）
  - 契約書類
  - その他（マニュアル等）
- [x] 保管のみが目的の書類を天袋にしまう。

**Comment by ytogo** [comment]
書類、取扱説明書、保証書などファイリングいたしました。
背表紙が手書きで見難いので、シールを作り分かりやすくしたいと思います。
よろしくお願いいたします。

**Comment by komagata** [comment]
> 背表紙が手書きで見難いので、シールを作り分かりやすくしたいと思います。

@ytogo お願いします！

**Comment by ytogo** [comment]
背表紙のラベルを作成しました。過去の書類のファイリング作業完了いたしました。
ご確認よろしくお願いいたします。

**Comment by komagata** [comment]
@ytogo 確認しました。ありがとうございます。
