### ISSUE TITLE
怖話ニュースのピックアップ方法をWikiにまとめる

### ISSUE THREAD

**Issue by komagata** [fjordllc/fjordllc#28]
怖話ニュースを見つけてきて書くのインターンに任せたいのでドキュメントを用意する。
ニュース投稿自体のドキュメントはあるので、ピックアップの流れなども追記して欲しい。

https://github.com/fjordllc/kowabana/wiki/%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9%E3%81%AE%E6%8A%95%E7%A8%BF%E6%96%B9%E6%B3%95

**Comment by ytogo** [comment]
ニュースをピックアップピックアップしてからの流れに
町田さんに確認してから、記事を書くことと
書いた記事の確認取ることを追加いたしますた。

https://github.com/fjordllc/kowabana/wiki/ニュースの投稿方法

**Comment by komagata** [comment]
👍

**Comment by komagata** [comment]
@ytogo インターンがわかるように下記に追記しました。

http://256interns.com/pages/%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%83%AF%E3%83%BC%E3%82%AF
