### ISSUE TITLE
住民税、年金の給与天引きの申し込み

### ISSUE THREAD

**Issue by machida** [fjordllc/fjordllc#34]
給料からの天引きになるものについて、税理士の先生に確認をお願いしたいです。

---

- 住民税
- 厚生年金
- 社会保険

などが、給料からの天引きになるものだと思います。

今年度は住民税は給料からの天引きに設定していなかったので、僕と駒形さんが個別に支払いを行っていましたが、今年度に社労士さんにお願いをしたので、来年度からは給料天引きになるようにしていただいたかと思います（ですよね？）。

---

- [ ] 上記に挙げた、住民税、厚生年金... などの給料からの天引きになる項目の中で、毎年度申し込みが必要なものの確認をお願いします。
-  [ ] 申し込みの方法の確認をお願いします。
-  [ ] それぞれの申し込みのタイミングの確認をし、それをGoogleカレンダーで共有をお願いします。

---

上記に含まれる内容になるのですが、社労士さんにお願いをした住民税については、

-  [ ] また来年度も社労士さんにお願いをする必要があるのか？
-  [ ] 必要がある場合、どのタイミングで依頼をしたらいいのか？

の確認をお願いします。

**Comment by ytogo** [comment]
かしこまりました。確認致します。

**Comment by machida** [comment]
@ytogo よろしくお願いします 🙏

**Comment by ytogo** [comment]
北島先生に伺ったところ、先生が今回の年末調整後に、各自治体へ給与支払報告書を電子上で提出してくださるそうです。
住民税はお給料から天引きされるようになり、書類も会社に来るようになるとのことです。
よろしくお願い致します。

**Comment by machida** [comment]
@ytogo ありがとうございます！
